version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: always
    environment:
      - BOT_INTRODUCTION_KEY=your_token_here
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge